# Generated by Django 3.1.3 on 2021-01-13 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_cart_cartitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='data_added',
            field=models.DateField(auto_now_add=True),
        ),
    ]
